name: Build PDFs
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: thomasweise/docker-texlive-full
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Make
        run: make
      - uses: actions/upload-artifact@v3
        with:
          name: thesis.pdf
          path: thesis.pdf
      - uses: actions/upload-artifact@v3
        with:
          name: abstract.pdf
          path: abstract.pdf