name: Build PDFs
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Make
        uses: dante-ev/latex-action@latest
        with:
          entrypoint: ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: thesis.pdf
          path: thesis.pdf
      - uses: actions/upload-artifact@v3
        with:
          name: abstract.pdf
          path: abstract.pdf